name: CI/CD Pipeline

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis: redis

    strategy:
      fail-fast: false
        python-version:
          - 3.7
          - 3.8
          - 3.9

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

          #    - name: Install dependencies
          #      run: |
          #        pip install -r requirements.txt
          #        pip install -r requirements-dev.txt

    - name: Run tests
      run: |
        make test

    - name: Run linter
      run: |
        make lint
